version: '3.4'

services:

    express_mysql:
        container_name: express_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "express"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "secret"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - express-network

networks:
    express-network:
        driver: bridge